[package]
name = "client-async-std"
version = "0.1.0"
edition = "2021"

[dependencies]
surf = { version = "2.3.2", features = ["h1-client"]}
async-std = { version = "1.12.0", features = ["attributes"]}
async-macros = { version = "2.0.0" }
serde = { version = "1.0", features = ["derive"]}
